// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mcp

import (
	"github.com/honeycarbs/project-ets/internal/config"
	"github.com/honeycarbs/project-ets/internal/domain/job"
	adzuna2 "github.com/honeycarbs/project-ets/internal/domain/job/providers/adzuna"
	neo4j2 "github.com/honeycarbs/project-ets/internal/storage/neo4j"
	"github.com/honeycarbs/project-ets/pkg/adzuna"
	"github.com/honeycarbs/project-ets/pkg/neo4j"
)

// Injectors from wire.go:

// InitializeToolDeps creates toolDeps with all dependencies wired up
func InitializeToolDeps(cfg config.Config) (*toolDeps, error) {
	neo4jConfig := provideNeo4jConfig(cfg)
	client, err := neo4j.NewClient(neo4jConfig)
	if err != nil {
		return nil, err
	}
	jobRepository := neo4j2.NewJobRepository(client)
	adzunaConfig := provideAdzunaConfig(cfg)
	adzunaClient, err := adzuna.NewClient(adzunaConfig)
	if err != nil {
		return nil, err
	}
	provider, err := provideAdzunaProvider(adzunaClient)
	if err != nil {
		return nil, err
	}
	v := provideJobProviders(provider)
	service, err := job.NewServiceWithDeps(jobRepository, v)
	if err != nil {
		return nil, err
	}
	mcpStubKeywordRepository := provideStubKeywordRepository()
	mcpStubAnalysisService := provideStubAnalysisService()
	mcpStubSheetsClient := provideStubSheetsClient()
	mcpToolDeps := newToolDeps(service, mcpStubKeywordRepository, mcpStubAnalysisService, mcpStubSheetsClient, client)
	return mcpToolDeps, nil
}

// wire.go:

// provideNeo4jConfig extracts Neo4j config from main config
func provideNeo4jConfig(cfg config.Config) neo4j.Config {
	return neo4j.Config{
		URI:      cfg.Neo4j.URI,
		Username: cfg.Neo4j.Username,
		Password: cfg.Neo4j.Password,
	}
}

// provideAdzunaConfig extracts Adzuna config from main config
func provideAdzunaConfig(cfg config.Config) adzuna.Config {
	return adzuna.Config{
		AppID:   cfg.Adzuna.AppID,
		AppKey:  cfg.Adzuna.AppKey,
		Country: cfg.Adzuna.Country,
	}
}

// provideAdzunaProvider creates an Adzuna provider from client
func provideAdzunaProvider(client *adzuna.Client) (*adzuna2.Provider, error) {
	return adzuna2.NewProvider(client)
}

// provideJobProviders creates a slice of job providers
func provideJobProviders(adzunaProvider *adzuna2.Provider) []job.Provider {
	return []job.Provider{adzunaProvider}
}

// provideStubKeywordRepository provides stub keyword repository
func provideStubKeywordRepository() stubKeywordRepository {
	return stubKeywordRepository{}
}

// provideStubAnalysisService provides stub analysis service
func provideStubAnalysisService() stubAnalysisService {
	return stubAnalysisService{}
}

// provideStubSheetsClient provides stub sheets client
func provideStubSheetsClient() stubSheetsClient {
	return stubSheetsClient{}
}

// newToolDeps creates toolDeps struct
func newToolDeps(
	jobService job.Service,
	keywordRepo stubKeywordRepository,
	analysisSvc stubAnalysisService,
	sheetsClient stubSheetsClient,
	neo4jClient *neo4j.Client,
) *toolDeps {
	return &toolDeps{
		jobService:   jobService,
		keywordRepo:  keywordRepo,
		analysisSvc:  analysisSvc,
		sheetsClient: sheetsClient,
		neo4jClient:  neo4jClient,
	}
}
