// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package mcp

import (
	"context"
	"fmt"

	"github.com/honeycarbs/project-ets/internal/config"
	"github.com/honeycarbs/project-ets/internal/domain/analysis"
	"github.com/honeycarbs/project-ets/internal/domain/job"
	adzuna2 "github.com/honeycarbs/project-ets/internal/domain/job/providers/adzuna"
	"github.com/honeycarbs/project-ets/internal/mcp/tools"
	"github.com/honeycarbs/project-ets/internal/repository"
	neo4j2 "github.com/honeycarbs/project-ets/internal/storage/neo4j"
	"github.com/honeycarbs/project-ets/pkg/adzuna"
	"github.com/honeycarbs/project-ets/pkg/logging"
	"github.com/honeycarbs/project-ets/pkg/neo4j"
	"github.com/honeycarbs/project-ets/pkg/sheets"
)

// Injectors from wire.go:

// InitializeResources creates Resources with all resources wired up
func InitializeResources(ctx context.Context, cfg config.Config, logger *logging.Logger) (*Resources, error) {
	neo4jConfig := provideNeo4jConfig(cfg)
	client, err := neo4j.NewClient(neo4jConfig)
	if err != nil {
		return nil, err
	}
	jobRepository := neo4j2.NewJobRepository(client)
	adzunaConfig := provideAdzunaConfig(cfg)
	adzunaClient, err := adzuna.NewClient(adzunaConfig)
	if err != nil {
		return nil, err
	}
	provider, err := provideAdzunaProvider(adzunaClient)
	if err != nil {
		return nil, err
	}
	v := provideJobProviders(provider)
	service, err := job.NewServiceWithDeps(jobRepository, v)
	if err != nil {
		return nil, err
	}
	keywordRepository := neo4j2.NewKeywordRepository(client)
	analysisRepository := neo4j2.NewAnalysisRepository(client, logger)
	analysisService := analysis.NewService(analysisRepository)
	sheetsConfig := provideSheetsConfig(cfg)
	sheetsClient, err := provideSheetsClient(ctx, sheetsConfig)
	if err != nil {
		return nil, err
	}
	toolsSheetsClient := provideSheetsClientAdapter(sheetsClient)
	resources := newResources(service, jobRepository, keywordRepository, analysisService, toolsSheetsClient, client)
	return resources, nil
}

// wire.go:

// provideNeo4jConfig extracts Neo4j config from main config
func provideNeo4jConfig(cfg config.Config) neo4j.Config {
	return neo4j.Config{
		URI:      cfg.Neo4j.URI,
		Username: cfg.Neo4j.Username,
		Password: cfg.Neo4j.Password,
	}
}

// provideAdzunaConfig extracts Adzuna config from main config
func provideAdzunaConfig(cfg config.Config) adzuna.Config {
	return adzuna.Config{
		AppID:   cfg.Adzuna.AppID,
		AppKey:  cfg.Adzuna.AppKey,
		Country: cfg.Adzuna.Country,
	}
}

// provideAdzunaProvider creates an Adzuna provider from client
func provideAdzunaProvider(client *adzuna.Client) (*adzuna2.Provider, error) {
	return adzuna2.NewProvider(client)
}

// provideJobProviders creates a slice of job providers
func provideJobProviders(adzunaProvider *adzuna2.Provider) []job.Provider {
	return []job.Provider{adzunaProvider}
}

// provideSheetsConfig extracts Sheets config from main config
func provideSheetsConfig(cfg config.Config) sheets.Config {
	return sheets.Config{
		CredentialsPath: cfg.Sheets.CredentialsPath,
	}
}

// provideSheetsClient creates a Sheets client
func provideSheetsClient(ctx context.Context, cfg sheets.Config) (*sheets.Client, error) {
	if cfg.CredentialsPath == "" {
		return nil, fmt.Errorf("sheets: GOOGLE_SHEETS_CREDENTIALS_PATH is not set")
	}
	return sheets.NewClient(ctx, cfg)
}

// provideSheetsClientAdapter creates a SheetsClient adapter
func provideSheetsClientAdapter(client *sheets.Client) tools.SheetsClient {
	return &sheetsClientAdapter{client: client}
}

// newResources creates Resources struct
func newResources(
	jobService job.Service,
	jobRepo repository.JobRepository,
	keywordRepo tools.KeywordRepository,
	analysisSvc tools.AnalysisService,
	sheetsClient tools.SheetsClient,
	neo4jClient *neo4j.Client,
) *Resources {
	return &Resources{
		JobService:   jobService,
		JobRepo:      jobRepo,
		KeywordRepo:  keywordRepo,
		AnalysisSvc:  analysisSvc,
		SheetsClient: sheetsClient,
		Neo4jClient:  neo4jClient,
	}
}
